require('plugin-config.treesitter')
require('plugin-config.lualine-config')
-- require('plugin-config.airline-config')
require('plugin-config.bufferline-config')
require('plugin-config.nvim-tree-config')
require('plugin-config.nvim-ts-autotag')
require('plugin-config.nvim-autopairs-config')
require('plugin-config.telescope-config')
require('plugin-config.gitsigns-config')
require('plugin-config.indent-blankline-config')
require('plugin-config.toggleterm-config')
require('plugin-config.nvim-comment-config')
